# OpenAI의 Embedding model 을 활용한 코사인 유사도 검색 시스템

In [ ]:
import os
import numpy as np
from numpy import dot
from numpy.linalg import norm
import pandas as pd
from langchain_openai import OpenAIEmbeddings

import config

In [ ]:
# "저는 배가 고파요" 라는 텍스트를 테스트 임베딩

embeddings = OpenAIEmbeddings(model=config.EMBEDDING_MODEL, openai_api_key=config.OPENAI_API_KEY)
query_result = embeddings.embed_query("저는 배가 고파요")
print(query_result)

[0.017364501953125, -0.0078582763671875, -0.0290985107421875, 0.0075531005859375, 0.00115203857421875, -0.058746337890625, -0.033721923828125, 0.033599853515625, -0.0467529296875, -0.01544189453125, -0.02069091796875, 0.051239013671875, -0.0013132095336914062, -0.0038471221923828125, -0.0169677734375, 0.002384185791015625, -0.05816650390625, 0.00034999847412109375, 0.004978179931640625, -0.03277587890625, -0.0245513916015625, -0.0157623291015625, -0.023284912109375, -0.006778717041015625, 0.0020580291748046875, -0.00034737586975097656, 0.039581298828125, -0.033721923828125, 0.0036334991455078125, -0.01157379150390625, 0.00989532470703125, -0.04766845703125, 0.0180511474609375, -0.0484619140625, -0.01898193359375, -0.0386962890625, 0.011688232421875, -0.037689208984375, -0.00418853759765625, 0.0011758804321289062, -0.029205322265625, 0.0015573501586914062, -0.0179901123046875, 0.008941650390625, 0.03289794921875, 0.036041259765625, -0.005748748779296875, 0.01514434814453125, 0.051727294921875, 0.00839996337890625, -0.014190673828125, 0.01036834716796875, 0.0093536376953125, 0.0609130859375, 0.031646728515625, 0.007701873779296875, -0.00168609619140625, 0.010894775390625, -0.016021728515625, -0.01219940185546875, -0.0163726806640625, 0.0074462890625, -0.0247039794921875, 0.02166748046875, -0.00396728515625, -0.019683837890625, 0.0302734375, -0.04364013671875, -0.013885498046875, 0.01183319091796875, 0.0066375732421875, -0.00687408447265625, -0.041900634765625, 0.0070953369140625, 0.0158233642578125, -0.00218963623046875, 0.0015592575073242188, -0.0268096923828125, 0.03887939453125, 0.0199432373046875, 0.020294189453125, 0.06829833984375, 0.0263519287109375, -0.05609130859375, -0.0209808349609375, -0.060791015625, -0.07110595703125, -0.000995635986328125, -0.01165771484375, 0.019866943359375, -0.01126861572265625, 0.0243682861328125, 0.0244140625, 0.019012451171875, -0.0268096923828125, -0.0009627342224121094, -0.002429962158203125, -0.0161285400390625, -0.004032135009765625, 0.01154327392578125, 0.03887939453125, 0.0277557373046875, 0.00897979736328125, 0.0052032470703125, 0.045745849609375, 0.004650115966796875, 0.01319122314453125, -0.0177001953125, -0.049652099609375, 0.010284423828125, -0.01812744140625, 0.034759521484375, 0.0206451416015625, -0.02349853515625, -0.02471923828125, 0.0309906005859375, 0.0084686279296875, 0.0006761550903320312, -0.0037517547607421875, -0.0537109375, 0.03765869140625, 0.042083740234375, 0.005649566650390625, -0.053985595703125, -0.0186004638671875, 0.007843017578125, -0.01837158203125, 0.00804901123046875, -0.03045654296875, 0.06439208984375, -0.00856781005859375, -0.0261383056640625, 0.03692626953125, -0.022796630859375, -0.0012845993041992188, 0.034149169921875, -0.03973388671875, -0.0187225341796875, -0.03228759765625, -0.0233154296875, 0.0243682861328125, 0.007633209228515625, 0.0207977294921875, -0.0012903213500976562, -0.0208587646484375, -0.025299072265625, 0.0285491943359375, 0.08685302734375, -0.01727294921875, 0.053955078125, 0.005756378173828125, 0.006961822509765625, -0.0256500244140625, -0.0287933349609375, -0.01294708251953125, -0.01343536376953125, -0.051239013671875, 0.061981201171875, -0.01029205322265625, 0.047821044921875, 0.01119232177734375, 0.00818634033203125, 0.0268707275390625, 0.019927978515625, -0.0008792877197265625, 0.0369873046875, -0.01165008544921875, 0.01541900634765625, -0.01200103759765625, -0.0330810546875, 0.0157470703125, 0.054718017578125, 0.010955810546875, -0.0300445556640625, -0.01468658447265625, -0.00624847412109375, 0.0007996559143066406, 0.039276123046875, -0.03851318359375, 0.021331787109375, -0.0007700920104980469, 0.0045013427734375, -0.007518768310546875, 0.0265960693359375, -0.035400390625, 0.006465911865234375, 0.071533203125, 0.041290283203125, -0.0022945404052734375, 0.00799560546875, 0.01209259033203125, 0.06195068359375, 0.0321044921875, -0.07232666015625, -0.03204345703125, -0.043365478515625, -0.01488494873046875, -0.050262451171875, -0.020721435546875, 0.02081298828125, 0.04742431640625, 0.01702880859375, 0.05401611328125, 0.0046844482421875, 0.0013418197631835938, 0.004589080810546875, -0.01520538330078125, -0.01629638671875, 0.0104217529296875, 0.007335662841796875, 0.0297088623046875, 0.0002758502960205078, -0.01503753662109375, 0.02252197265625, -0.0172882080078125, -0.0301971435546875, 0.083984375, 0.041473388671875, 0.033905029296875, 0.0290985107421875, 0.01861572265625, -0.0178375244140625, 0.0169677734375, -0.001079559326171875, 0.040771484375, 0.0506591796875, 0.06304931640625, -0.0164794921875, -0.00194549560546875, 0.0087890625, -0.01099395751953125, 0.041107177734375, -0.0099334716796875, -0.0452880859375, -0.0418701171875, 0.0299072265625, -0.0054168701171875, 0.00579071044921875, 0.0164794921875, -0.0286865234375, 0.00867462158203125, 0.046600341796875, 0.03887939453125, -0.00972747802734375, -0.010040283203125, 0.00817108154296875, 0.01263427734375, 0.0068511962890625, 0.018463134765625, 0.0548095703125, 0.02398681640625, 0.0296630859375, -0.0017843246459960938, -0.00615692138671875, -0.0259246826171875, 0.0086822509765625, -0.00811004638671875, 0.0044403076171875, -0.03631591796875, 0.004119873046875, 0.0439453125, -0.00652313232421875, -0.042816162109375, 0.011566162109375, -0.00183868408203125, 0.014312744140625, 0.057037353515625, -0.01398468017578125, 0.031494140625, 2.777576446533203e-05, -0.01081085205078125, -0.011505126953125, -0.0045928955078125, -0.0249176025390625, -0.04132080078125, 0.0085906982421875, -0.03173828125, 0.0031147003173828125, 0.01227569580078125, -0.05206298828125, -0.0009703636169433594, 0.0175323486328125, -0.01214599609375, -0.039031982421875, -0.010040283203125, 0.03643798828125, -0.02081298828125, 0.0096435546875, 0.0440673828125, -0.0267791748046875, 0.0218505859375, -0.0260162353515625, 0.004974365234375, 0.02197265625, 0.059417724609375, 0.01068115234375, 0.0088958740234375, 0.005077362060546875, 0.0306396484375, -0.0224456787109375, 0.038330078125, 0.0089263916015625, -0.00936126708984375, -0.006290435791015625, -0.02825927734375, -0.017913818359375, -0.0026187896728515625, -0.0035495758056640625, -0.0509033203125, 0.003009796142578125, -0.050689697265625, -0.01367950439453125, 0.041595458984375, -0.034637451171875, -0.002918243408203125, -0.00832366943359375, 0.01140594482421875, -0.014007568359375, 0.01479339599609375, -0.0171051025390625, 0.0584716796875, 0.0281982421875, -0.036346435546875, 0.062255859375, -0.005733489990234375, 0.0020084381103515625, 0.0238800048828125, -0.01418304443359375, 0.004772186279296875, -0.02545166015625, -0.034759521484375, 0.013336181640625, 0.0382080078125, -0.02587890625, 0.0259552001953125, -0.04473876953125, 0.017242431640625, -0.007389068603515625, -0.020599365234375, -0.0294342041015625, -0.0293731689453125, 0.005855560302734375, -0.01010894775390625, 0.0101776123046875, 0.002490997314453125, 0.03076171875, 0.063232421875, -0.0294952392578125, -0.035064697265625, -0.0328369140625, 0.06536865234375, 0.0022125244140625, 0.042266845703125, -0.01342010498046875, -0.005367279052734375, -0.0357666015625, 0.0150909423828125, 0.030487060546875, 0.00031638145446777344, 0.04632568359375, -0.061370849609375, 0.0089874267578125, -0.01444244384765625, -0.02197265625, 0.00365447998046875, -0.0161285400390625, -0.025970458984375, 0.01053619384765625, 0.0236968994140625, 0.042388916015625, -0.0289306640625, 0.0054931640625, -0.022369384765625, -0.001071929931640625, -0.0150909423828125, 0.00704193115234375, 0.0246734619140625, 0.0418701171875, -0.0246429443359375, 0.00875091552734375, -0.00960540771484375, 0.0169525146484375, -0.012939453125, 0.049774169921875, -0.00879669189453125, -0.035552978515625, -0.015472412109375, 0.0325927734375, 0.0278167724609375, 0.034576416015625, 0.0576171875, -0.004047393798828125, -0.005374908447265625, -0.0007562637329101562, -0.0352783203125, 0.0240478515625, -0.016571044921875, -0.0175628662109375, -0.059295654296875, -0.0268402099609375, -0.019866943359375, 0.0044097900390625, -0.06524658203125, -0.037109375, 0.0126953125, 0.00965118408203125, -0.039581298828125, 0.035003662109375, -0.007236480712890625, -0.03009033203125, 0.0167694091796875, 0.048675537109375, 0.04998779296875, 0.01235198974609375, 0.040496826171875, -0.0018405914306640625, -0.0127410888671875, 0.027252197265625, -0.00897216796875, 0.004642486572265625, 0.041534423828125, 0.06170654296875, -0.0543212890625, 0.00464630126953125, -0.057159423828125, 0.00254058837890625, 0.0011148452758789062, -0.005596160888671875, 0.06536865234375, -0.03271484375, 0.0249176025390625, 0.01324462890625, -0.03936767578125, -0.0103302001953125, -0.01092529296875, -0.07708740234375, -0.003910064697265625, 0.0166168212890625, 0.002826690673828125, -0.0241851806640625, 0.01305389404296875, -0.08489990234375, -0.01404571533203125, 0.0380859375, -0.021270751953125, 0.01446533203125, 0.0404052734375, -0.01200103759765625, -0.00940704345703125, -0.0229034423828125, 0.0496826171875, -0.0123138427734375, -0.005947113037109375, -0.0012826919555664062, -0.0207366943359375, 0.01149749755859375, 0.00030422210693359375, 0.01192474365234375, 0.018463134765625, -0.050048828125, -0.005123138427734375, 0.0438232421875, -0.0038967132568359375, 0.0199737548828125, 0.01468658447265625, -0.00984954833984375, 0.0173492431640625, 0.021759033203125, 0.00368499755859375, 0.004688262939453125, 0.00360107421875, 0.0156402587890625, -0.033355712890625, -0.044891357421875, 0.01108551025390625, 0.0299072265625, -0.070068359375, 0.004314422607421875, -0.0283660888671875, -0.0234375, 0.0062713623046875, 0.04547119140625, -0.0182647705078125, -0.02398681640625, 0.0031223297119140625, 0.108154296875, -0.007511138916015625, 0.02264404296875, -0.05206298828125, -0.031951904296875, 0.0214996337890625, 0.0013246536254882812, 0.068115234375, -0.0037078857421875, -0.010009765625, 0.006298065185546875, -0.074462890625, -0.013275146484375, -0.00930023193359375, 0.0026531219482421875, -0.0160675048828125, -0.01727294921875, 0.00231170654296875, -0.0175933837890625, 0.035369873046875, -0.005054473876953125, -0.00963592529296875, 0.01053619384765625, -0.00978851318359375, -0.00553131103515625, -0.01393890380859375, 0.0273284912109375, -0.01476287841796875, -0.00041961669921875, 0.01898193359375, -0.00269317626953125, -0.0015344619750976562, -0.016265869140625, 0.0175933837890625, 0.059326171875, -0.0299835205078125, -0.0046234130859375, 0.01525115966796875, -0.036895751953125, -0.004695892333984375, -0.0258636474609375, -0.002178192138671875, 0.0006208419799804688, 0.01012420654296875, 0.009185791015625, 0.004940032958984375, 0.0111541748046875, -0.01788330078125, -0.0302886962890625, -0.0082550048828125, -0.03314208984375, 0.00467681884765625, 0.0028095245361328125, 0.0107879638671875, 0.0206451416015625, -0.01558685302734375, -0.0011339187622070312, -0.038665771484375, 0.007442474365234375, 0.00324249267578125, -0.01023101806640625, 0.00848388671875, -0.02801513671875, 0.049896240234375, 0.047119140625, 0.00811767578125, -0.0012598037719726562, -0.0115509033203125, 0.0271148681640625, -0.02667236328125, -0.0261077880859375, -0.0145721435546875, 0.01324462890625, 0.0192718505859375, 0.034271240234375, -0.011138916015625, 0.010040283203125, 0.0281829833984375, 0.005748748779296875, -0.002536773681640625, -0.0307769775390625, 5.251169204711914e-05, -0.038482666015625, -0.01898193359375, 0.004817962646484375, -0.016937255859375, 0.037506103515625, -0.025238037109375, 0.0196685791015625, 0.007236480712890625, -0.01812744140625, 0.05694580078125, -0.0011234283447265625, -0.06085205078125, 0.0419921875, -0.033233642578125, -0.038909912109375, -0.0263519287109375, -0.0212860107421875, -0.025115966796875, 0.0069580078125, -0.038665771484375, -0.00864410400390625, 0.018798828125, -0.0070953369140625, 0.023284912109375, -0.007793426513671875, -0.006961822509765625, 0.00179290771484375, 0.01140594482421875, -0.0447998046875, -0.0357666015625, -0.00848388671875, 0.0229339599609375, -0.0174560546875, -0.0072021484375, -0.041839599609375, 0.020416259765625, 0.0210723876953125, 0.0140228271484375, -0.026275634765625, -0.0176849365234375, 0.00809478759765625, 0.0172576904296875, 0.01332855224609375, 0.003818511962890625, -0.01406097412109375, -0.0214385986328125, -0.0254669189453125, 0.00606536865234375, 0.0162811279296875, -0.03643798828125, -0.01027679443359375, -0.0007615089416503906, 0.0258026123046875, -0.00667572021484375, 0.02838134765625, 0.022674560546875, 0.0041656494140625, -0.020721435546875, 0.01259613037109375, 0.011505126953125, 0.022552490234375, -0.01300048828125, -0.003635406494140625, 0.005725860595703125, -0.058197021484375, -0.00830841064453125, 0.0225372314453125, 0.0019521713256835938, 0.0069732666015625, -0.004364013671875, -0.00945281982421875, -0.00775909423828125, 0.03167724609375, 0.0143280029296875, -0.0218353271484375, 0.01203155517578125, -0.0233612060546875, -0.01273345947265625, 0.03521728515625, -0.011749267578125, 0.01049041748046875, -0.005611419677734375, -0.0173797607421875, 0.049224853515625, 0.0167694091796875, -0.0025081634521484375, -0.0167236328125, -0.0217742919921875, 0.01922607421875, -0.019683837890625, -0.01385498046875, -0.003498077392578125, -0.00383758544921875, -0.0029354095458984375, 0.002483367919921875, -0.0108795166015625, -0.00655364990234375, 0.01467132568359375, 0.0251007080078125, -0.0186614990234375, 0.050323486328125, 0.006816864013671875, 0.008453369140625, 0.043792724609375, -0.0059661865234375, -0.00445556640625, -0.0017490386962890625, 0.052154541015625, 0.031829833984375, -0.0267181396484375, -0.01049041748046875, -0.0205230712890625, 0.024749755859375, -0.002231597900390625, 0.02606201171875, 0.0069122314453125, -0.0264892578125, 0.052886962890625, -0.0065155029296875, -0.01104736328125, -0.0115203857421875, 0.049285888671875, 0.004730224609375, -0.02117919921875, 0.0283355712890625, -0.004093170166015625, -0.0198974609375, 0.0040740966796875, 0.0230865478515625, 0.02099609375, -0.048095703125, -0.00438690185546875, 0.031707763671875, -0.01346588134765625, 0.00988006591796875, -0.01210784912109375, -0.0014524459838867188, -0.0099945068359375, 0.0077056884765625, 0.035614013671875, 0.012481689453125, 0.0011758804321289062, -0.03985595703125, -0.00452423095703125, -0.007144927978515625, -0.042694091796875, 0.0230255126953125, 0.0097198486328125, 0.020355224609375, -0.020599365234375, -0.019622802734375, -0.0241851806640625, -0.035552978515625, -0.0079193115234375, 0.053558349609375, -0.01438140869140625, -0.01110076904296875, 0.0095672607421875, -0.0364990234375, -0.021484375, -0.0025653839111328125, -0.013427734375, 0.01099395751953125, -0.00481414794921875, 0.012451171875, -0.0278167724609375, 0.0231475830078125, 0.0003476142883300781, 0.0247650146484375, -0.0355224609375, -0.012664794921875, 0.0244140625, -0.007686614990234375, -0.04315185546875, -0.03143310546875, 0.0123138427734375, -0.0158843994140625, 0.00197601318359375, 0.0186767578125, 0.001781463623046875, -9.709596633911133e-05, -0.01195526123046875, -0.031097412109375, -0.021392822265625, 0.0014219284057617188, 0.0202178955078125, -0.00786590576171875, 0.0262908935546875, 0.006259918212890625, 0.02734375, -0.06695556640625, 0.02899169921875, 0.00806427001953125, 0.04742431640625, -0.02081298828125, -0.025543212890625, 0.031494140625, 0.02862548828125, -0.0274200439453125, -0.00977325439453125, -0.0228118896484375, 0.000492095947265625, 0.01837158203125, 0.013153076171875, -0.0091094970703125, 0.037200927734375, 0.0053253173828125, 0.0251007080078125, -0.02532958984375, -0.0142059326171875, -0.006134033203125, 0.034698486328125, -0.01422119140625, 0.005664825439453125, -0.00441741943359375, -0.0214385986328125, 0.019989013671875, -0.02642822265625, -0.009918212890625, -0.01702880859375, -0.000865936279296875, -0.030853271484375, 0.018157958984375, -0.0217742919921875, -0.0236663818359375, -0.029937744140625, -0.007091522216796875, 0.0038623809814453125, 0.052001953125, 0.0037403106689453125, 0.0032978057861328125, -0.0177001953125, -0.019989013671875, 0.0167388916015625, -0.0294189453125, 0.043426513671875, -0.01052093505859375, 0.0061798095703125, -0.00262451171875, 0.0352783203125, 0.054168701171875, 0.0148468017578125, -0.037384033203125, 0.0010433197021484375, 0.0084991455078125, 0.01129150390625, 0.04071044921875, 0.001384735107421875, -0.00417327880859375, 0.005828857421875, -0.010772705078125, -0.006298065185546875, -0.0255279541015625, -0.00859832763671875, -0.01161956787109375, 0.0221710205078125, -0.0158843994140625, -0.01444244384765625, -0.0212860107421875, -0.0159149169921875, 0.005840301513671875, 0.026580810546875, 0.0684814453125, 0.01654052734375, -0.016357421875, -0.0268707275390625, -0.00508880615234375, -0.028900146484375, 0.0295867919921875, 0.051727294921875, -0.0103607177734375, -0.0012388229370117188, -0.0008068084716796875, -0.01349639892578125, 0.0156402587890625, 0.0313720703125, -0.019500732421875, -0.05120849609375, -0.0163726806640625, -0.0626220703125, 0.0004775524139404297, 0.0187225341796875, -0.0250396728515625, -0.0077362060546875, 0.00345611572265625, -0.002414703369140625, 0.005619049072265625, 0.03912353515625, 0.0008721351623535156, 0.037109375, 0.038238525390625, 0.0196380615234375, -0.0579833984375, -0.050933837890625, 0.02520751953125, -0.010772705078125, 0.022613525390625, 0.0007715225219726562, -0.0098419189453125, 0.00514984130859375, 0.0004096031188964844, -0.02423095703125, 0.0185394287109375, -0.029632568359375, -0.00269317626953125, -0.0226593017578125, -0.044525146484375, -0.002277374267578125, -0.004119873046875, -0.0031986236572265625, -0.0184173583984375, 0.004726409912109375, 0.0002371072769165039, 0.000762939453125, -0.035125732421875, 0.0173492431640625, 0.0269775390625, 0.0164642333984375, 0.019683837890625, 0.026519775390625, 0.0286712646484375, -0.01558685302734375, 0.03118896484375, -0.00860595703125, -0.0108489990234375, 0.00203704833984375, -0.0308990478515625, -0.0106658935546875, 0.00199127197265625, -0.0149383544921875, 0.03497314453125, 0.01273345947265625, -0.0419921875, 0.0190582275390625, 0.013427734375, 0.004535675048828125, -0.0014553070068359375, 0.0239105224609375, 0.00791168212890625, -0.031158447265625, 0.0151824951171875, 0.01100921630859375, -0.0306243896484375, 0.0110931396484375, 0.0034961700439453125, -0.0096435546875, 0.0014657974243164062, -0.0060272216796875, 0.00494384765625, -0.025543212890625, 0.03558349609375, -0.006290435791015625, -0.007099151611328125, -0.0364990234375, -0.01296234130859375, 0.005542755126953125, -0.00400543212890625, -0.004241943359375, -0.0187835693359375, -0.0011396408081054688, 0.01105499267578125, -0.0657958984375, 0.011077880859375, -0.006870269775390625, -0.0132598876953125, -0.001377105712890625, 0.010986328125, 0.033538818359375, -0.017425537109375, -0.0021381378173828125, -0.0165863037109375, -0.0244293212890625, -0.00888824462890625, -0.0205535888671875, 0.035247802734375, 0.0241851806640625, -0.02447509765625, 0.0242156982421875, -0.020233154296875, 0.0479736328125, -0.0032062530517578125, -0.0237274169921875, 0.0210113525390625, 0.0283660888671875, -0.034393310546875, -0.02191162109375, -0.029998779296875, 0.0311737060546875, 0.018157958984375, 0.037689208984375, -0.0079345703125, 0.00711822509765625, 0.01374053955078125, -0.0235748291015625, -0.03778076171875, -0.007205963134765625, -0.0633544921875, -0.026763916015625, -0.05401611328125, -0.014312744140625, -0.0213623046875, 0.035888671875, 0.02740478515625, -0.045745849609375, -0.01898193359375, 0.0269317626953125, 0.0260162353515625, 0.0283660888671875, -0.01031494140625, 0.004367828369140625, -0.015289306640625, -0.00905609130859375, 0.0171356201171875, 0.00457763671875, 0.021636962890625, 0.033355712890625, -0.007411956787109375, -0.0201568603515625, 0.0167694091796875, 0.062042236328125, -0.041717529296875, -0.0166168212890625, -0.027008056640625, 0.0207366943359375, 0.0268402099609375, 0.0247802734375, 0.019134521484375, 0.

In [ ]:
# 6개의 문장을 임베딩해 pandas 표로 출력

data = ['저는 배가 고파요',
        '저기 배가 지나가네요',
        '굶어서 허기가 지네요',
        '허기 워기라는 게임이 있는데 즐거워',
        '스팀에서 재밌는 거 해야지',
        '스팀에어프라이어로 연어구이 해먹을거야']

df = pd.DataFrame(data, columns=['text'])
df

                   text
0             저는 배가 고파요
1           저기 배가 지나가네요
2           굶어서 허기가 지네요
3   허기 워기라는 게임이 있는데 즐거워
4        스팀에서 재밌는 거 해야지
5  스팀에어프라이어로 연어구이 해먹을거야

In [ ]:
# 문장을 임베딩 해주는 get_embedding 함수와 df 데이터를 행 단위로 embedding apply

def get_embedding(text):
    return embeddings.embed_query(text)

df['embedding'] = df.apply(lambda row:get_embedding(row.text), axis=1)
df

                   text                                          embedding
0             저는 배가 고파요  [0.017364501953125, -0.0078582763671875, -0.02...
1           저기 배가 지나가네요  [0.03948974609375, 8.654594421386719e-05, -0.0...
2           굶어서 허기가 지네요  [0.041534423828125, 0.0248260498046875, -0.012...
3   허기 워기라는 게임이 있는데 즐거워  [0.00748443603515625, -0.00396728515625, -0.06...
4        스팀에서 재밌는 거 해야지  [0.01322174072265625, 0.05426025390625, -0.040...
5  스팀에어프라이어로 연어구이 해먹을거야  [0.050018310546875, 0.0038051605224609375, 0.0...

In [ ]:
# 코사인 유사도를 출력하는 함수 cos_sim 과, df 와 query(입력값) 의 유사도를 비교하는 함수 (내림차순 3개 출력)

def cos_sim(A,B):
    return dot(A, B)/(norm(A)*norm(B))

def return_answer_candidate(df, query):
    query_embedding = get_embedding(query)
    df["similarity"] = df.embedding.apply(
        lambda x:cos_sim(np.array(x), np.array(query_embedding)))
    top_three_doc = df.sort_values("similarity", ascending=False).head(3)
    return top_three_doc

In [ ]:
# 테스트용 문장을 입력하고 유사도가 높은 문장을 확인

sim_result = return_answer_candidate(df,'아무것도 안 먹었더니 꼬르륵 소리가 나네')
sim_result

,text,embedding,similarity
5,스팀에어프라이어로 연어구이 해먹을거야,"[0.050018310546875, 0.0038051605224609375, 0.0...",0.322957
0,저는 배가 고파요,"[0.017364501953125, -0.0078582763671875, -0.02...",0.247882
4,스팀에서 재밌는 거 해야지,"[0.01322174072265625, 0.05426025390625, -0.040...",0.225850

In [ ]:
# 두가지 모델을 비교해 높은 유사도를 확인해 보았음.

# 5 0 4 [text-embedding-3-small]
# 2 5 0 [text-embedding-ada-002]